// Proves the format-agnostic core: markers are ordinary comments in the
// target file's own format. The same fragment syncs into HTML, CSS/JS,
// YAML/shell line comments, Markdown, and config-defined formats — each
// target staying valid in its native syntax.

use std::fs;
use std::path::Path;

fn setup(dir: &Path, fragments: &[(&str, &str)], targets: &[(&str, &str)]) {
    let frag_dir = dir.join("_fragments");
    fs::create_dir_all(&frag_dir).unwrap();
    for (name, content) in fragments {
        fs::write(frag_dir.join(name), content).unwrap();
    }
    for (name, content) in targets {
        let path = dir.join(name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, content).unwrap();
    }
}

fn run(dir: &Path, cmd: &str) -> std::process::Output {
    std::process::Command::new(env!("CARGO_BIN_EXE_fragments"))
        .arg(dir.to_str().unwrap())
        .arg(cmd)
        .output()
        .expect("failed to run fragments")
}

fn read(dir: &Path, name: &str) -> String {
    fs::read_to_string(dir.join(name)).unwrap()
}

#[test]
fn syncs_into_css_block_comments() {
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("banner.css", ".banner { color: rebeccapurple; }")],
        &[(
            "style.css",
            "body { margin: 0; }\n/* fragment:banner */\n.banner { color: red; }\n/* /fragment:banner */\n",
        )],
    );

    assert!(run(root, "sync").status.success());
    let out = read(root, "style.css");
    assert!(out.contains(".banner { color: rebeccapurple; }"), "{out}");
    assert!(!out.contains("color: red"), "{out}");
    // Markers preserved, file still valid CSS.
    assert!(out.contains("/* fragment:banner */"));
    assert!(out.contains("/* /fragment:banner */"));
}

#[test]
fn syncs_into_yaml_line_comments() {
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("meta.yaml", "author: felix\nlicense: MIT")],
        &[(
            "config.yaml",
            "name: site\n# fragment:meta\nauthor: old\n# /fragment:meta\nport: 8080\n",
        )],
    );

    assert!(run(root, "sync").status.success());
    let out = read(root, "config.yaml");
    assert!(out.contains("author: felix"), "{out}");
    assert!(out.contains("license: MIT"), "{out}");
    assert!(!out.contains("author: old"), "{out}");
    // Surrounding YAML untouched.
    assert!(out.contains("name: site"));
    assert!(out.contains("port: 8080"));
    assert!(out.contains("# fragment:meta"));
    assert!(out.contains("# /fragment:meta"));
}

#[test]
fn syncs_into_markdown() {
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("footer.md", "---\n_Generated by fragments._")],
        &[(
            "README.md",
            "# Title\n\n<!-- fragment:footer -->\nold\n<!-- /fragment:footer -->\n",
        )],
    );

    assert!(run(root, "sync").status.success());
    let out = read(root, "README.md");
    assert!(out.contains("_Generated by fragments._"), "{out}");
    assert!(!out.contains("\nold\n"), "{out}");
}

#[test]
fn same_fragment_syncs_across_every_format() {
    // The headline: ONE fragment, three target formats, three comment syntaxes.
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("notice.txt", "DO NOT EDIT — managed by fragments")],
        &[
            (
                "index.html",
                "<!-- fragment:notice -->\nx\n<!-- /fragment:notice -->",
            ),
            (
                "app.css",
                "/* fragment:notice */\nx\n/* /fragment:notice */",
            ),
            (
                "deploy.sh",
                "#!/bin/sh\n# fragment:notice\nx\n# /fragment:notice\necho hi",
            ),
        ],
    );

    assert!(run(root, "sync").status.success());
    let needle = "DO NOT EDIT — managed by fragments";
    assert!(read(root, "index.html").contains(needle));
    assert!(read(root, "app.css").contains(needle));
    let sh = read(root, "deploy.sh");
    assert!(sh.contains(needle), "{sh}");
    // Shell file remains valid: shebang and trailing command intact.
    assert!(sh.starts_with("#!/bin/sh"));
    assert!(sh.contains("echo hi"));
}

#[test]
fn line_comment_name_boundary_is_respected() {
    // `nav` must not bleed into `navbar`: line-comment markers are
    // terminated by end-of-line, so prefix collisions can't happen.
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("nav.txt", "NAV"), ("navbar.txt", "NAVBAR")],
        &[(
            "page.sh",
            "# fragment:navbar\nold-bar\n# /fragment:navbar\n# fragment:nav\nold-nav\n# /fragment:nav\n",
        )],
    );

    assert!(run(root, "sync").status.success());
    let out = read(root, "page.sh");
    // Both regions filled with their own content, neither cross-contaminated.
    assert!(out.contains("NAVBAR"), "{out}");
    assert!(
        out.contains("# fragment:nav\nNAV\n# /fragment:nav"),
        "{out}"
    );
    assert!(!out.contains("old-nav"), "{out}");
    assert!(!out.contains("old-bar"), "{out}");
}

#[test]
fn duplicate_fragment_name_is_an_error() {
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    // header.html and header.css both resolve to the name "header".
    setup(
        root,
        &[("header.html", "<h1>h</h1>"), ("header.css", ".h{}")],
        &[(
            "index.html",
            "<!-- fragment:header -->\nx\n<!-- /fragment:header -->",
        )],
    );

    let out = run(root, "sync");
    assert!(!out.status.success(), "duplicate name should fail");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("duplicate fragment name"), "stderr: {err}");
}

#[test]
fn config_syntax_override_enables_unknown_format() {
    // Nunjucks `.njk` has no built-in syntax; declare it in fragments.toml.
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    fs::write(
        root.join("fragments.toml"),
        "[syntax]\nnjk = [\"{#\", \"#}\"]\n",
    )
    .unwrap();
    setup(
        root,
        &[("foot.txt", "© 2026")],
        &[(
            "page.njk",
            "{# fragment:foot #}\nold\n{# /fragment:foot #}\n",
        )],
    );

    assert!(run(root, "sync").status.success());
    let out = read(root, "page.njk");
    assert!(out.contains("© 2026"), "{out}");
    assert!(!out.contains("\nold\n"), "{out}");
}

#[test]
fn check_detects_stale_css() {
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    setup(
        root,
        &[("banner.css", "NEW")],
        &[(
            "style.css",
            "/* fragment:banner */\nOLD\n/* /fragment:banner */",
        )],
    );

    let out = run(root, "check");
    assert!(!out.status.success(), "stale css should fail check");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("stale"), "stderr: {err}");
}

#[test]
fn unknown_format_is_left_untouched() {
    // A .txt target has no comment syntax → invisible to fragments even if
    // it superficially contains marker-looking text.
    let tmp = tempfile::TempDir::new().unwrap();
    let root = tmp.path();
    let original = "<!-- fragment:x -->\nstays\n<!-- /fragment:x -->";
    setup(root, &[("x.html", "REPLACED")], &[("notes.txt", original)]);

    assert!(run(root, "sync").status.success());
    assert_eq!(read(root, "notes.txt"), original);
}
